### PR TITLE
Support DOMJudge 5.0.0.

### PR DESCRIPTION
**Pull request by nya3jp**
Minimally tested by installing generated *.deb to clean Ubuntu 14.04 system and judging one solution.

### CODE REVIEW

**Comment by thijskh** [comment]
Great, thanks!

**Comment by nya3jp** [comment]
Thanks for merging! Since it is easier to install, it is great to have Debian packages for DOMJudge 5. Do you plan to release it in official DOMJudge Debian repository?

**Comment by thijskh** [comment]
Yes, I plan to build those this weekend!

**Comment by nya3jp** [comment]
Great to hear that. Thank you!

**Pull request merged**
