### PR TITLE
Install additional PHP versions

### PR DESCRIPTION
**Pull request by vmcj**

### CODE REVIEW

**Review by nickygerritsen — APPROVED** [review]
If we do this for the contributor image we should maybe make a way to easily switch to another version, both for FPM and CLI?

**Comment by vmcj** [comment]
> If we do this for the contributor image we should maybe make a way to easily switch to another version, both for FPM and CLI?

I thought about that, but as there is `update-alternative --config php` I think that is good enough?

**Comment by nickygerritsen** [comment]
> > If we do this for the contributor image we should maybe make a way to easily switch to another version, both for FPM and CLI?
> 
> I thought about that, but as there is `update-alternative --config php` I think that is good enough?

That doesn’t work for FPM I think? Or is that also a binary we can switch that way?

**Comment by vmcj** [comment]
> > > If we do this for the contributor image we should maybe make a way to easily switch to another version, both for FPM and CLI?
> > 
> > 
> > I thought about that, but as there is `update-alternative --config php` I think that is good enough?
> 
> That doesn’t work for FPM I think? Or is that also a binary we can switch that way?

Currently I only use the php binary for phpunit, if we would also want to use it for fpm we could copy the /etc/php/7.4/fpm/pool.d for the other directories (/etc/php/{7,8}.{0,1,2,3,4}) and then restart the `service php8.1-fpm`. I haven't done that yet so prefer to do that in another PR.

**Comment by nickygerritsen** [comment]
Own PR is fine. I do think it’s nice for development to use the different versions for the web app

**Comment by vmcj** [comment]
> Own PR is fine. I do think it’s nice for development to use the different versions for the web app

I'll first see if we can get DJ8.0 with PHP8.0 support according to the Unit tests and then see if this is easily doable.

**Pull request merged**
