### PR TITLE
Shellcheck exclude

### PR DESCRIPTION
**Pull request by vmcj**

### CODE REVIEW

**Review by nickygerritsen — APPROVED** [review]

**Review by eldering — COMMENTED** [review]
I don't think we should ignore these paths. What's the reason to do so?

**Review by Dup4 — APPROVED** [review]

**Comment by vmcj** [comment]
> I don't think we should ignore these paths. What's the reason to do so?

Currently we would be in a broken state, I rather first get to a working state again and then slowly add the fixes.

The live-image hasn't been used for a while, we don't have a proper test and just applying most of these fixes over it might actually break it. So I rather had your opinion on these fixes and if it was needed.

In my experience shellcheck does not work well with the debian packaging (I might be wrong though) so that one I also rather exclude

**Comment by vmcj** [comment]
@eldering are you fine with me merging this to make the pipeline green again and we fix the scripts in the future so these directories can be in scope again?

**Comment by eldering** [comment]
> @eldering are you fine with me merging this to make the pipeline green again and we fix the scripts in the future so these directories can be in scope again?

I prever that we just fix the scripts that shellcheck has warnings about. There's not that much left.

**Pull request closed without merging**
